# Additional Curricula

Additional resources and curricula that may be of interest to instructors teaching the miniCURE. If you've got something to add, [let us know](https://help.c-moor.org)! The C-MOOR team has not reviewed all of these materials, but we are happy to share resources that you find helpful. 

Also don't forget to check [CourseSource](https://qubeshub.org/community/groups/coursesource/) for a large collection of biology curricula covering a wide range of topics, including many CUREs.

### Additional C-MOOR Curricula{-}

miniCUREs and CUREs by the C-MOOR team, covering different types of bioinformatic analyses. [Contact us](https://help.c-moor.org) if you’d be interested in partnering with us to develop and test these materials.

|Name|Topic(s)|Length|Status|
|------------|----------|----|----|
|[16S Microbiome miniCURE](https://science.c-moor.org/miniCURE-16S-Microbiome)|Microbiome|3 labs + Project Work|Under development|
|[Microbial Mysteries](https://science.c-moor.org/CURE-MicrobialMysteries)|Metagenomics|1 semester|beta-testing|
|scRNA-seq CURE|Single-cell RNA-seq|1 semester|piloted|

### Expanding on the RNA-seq Process{-}

Additional CUREs for instructors who wish to explore different research questions or go into more depth on various parts of the RNA-seq process.

|Name/Research Topic|Length|Wet Lab|Computing|
|---------------|-------|:----:|:------:|
|[Maize response to abiotic stress](https://doi.org/10.1187/cbe.15-04-0081)|3 weeks|**Yes**|**Yes** (R)|
|[Effect of sequencing quality on inference of sex differences in gene expression in human placenta](https://doi.org/10.1371/journal.pcbi.1012384)|7.5 weeks CURE, required 7.5 week pre-req computing course|**No**|**Yes** (R)|
|[Plant response to light](https://doi.org/10.1187/cbe.18-08-0161)|1 semester|**Yes**|**Yes** (Cyverse,R)|
|[Yeast environmental stress response](https://doi.org/10.1128/jmbe.v18i1.1226)|2 semesters|**Yes**|?|

### Other Genomics miniCUREs{-}

miniCUREs focusing on different types of genomic analyses.

|Name/Research Topic|Length|Wet Lab|Computing|
|---------------|-------|:----:|:------:|
|[Genomics Education Partnership (*Drosophila* genomics)](https://thegep.org/)|flexible|**No**|**Yes** (many options)|
|[Nanopore Sequencing to Assemble and Compare Chloroplast Genomes](https://doi.org/10.24918/cs.2026.3)|2-3 weeks|**Yes**|**Yes** (Notebook-based pipeline)|
|[Allen Brain Map](https://pubmed.ncbi.nlm.nih.gov/34552441/)|4 weeks|**No**|**Yes** (GUI)|
|[San Diego Biodiversity Project (DNA barcoding of invertebrates)](https://doi.org/10.1187/cbe.18-03-0046)|1 month|**Yes**|**Yes** (varied across institutions)|
|[Bean Beetle Microbiome Project](https://doi.org/10.3389/fmicb.2020.577621)|6 weeks or 12 weeks|**Yes**|**Yes** (6-week:BLAST, 12-week:DNA Subway, R)|

### Diving Deeper into R{-}

We recommend thinking carefully about your goals for students with regards to coding and RNA-seq analysis, and where the miniCURE fits in their journey.
We know this miniCURE only brushes the surface, and it is very tempting to add more.
For our first-year students, we found that backing off on the coding helped give them bandwidth to concentrate on the biology and scientific thinking, with the goal of attracting them to semester-long classes that have space to go deeper.
If you would like to dive a bit deeper into R, here are some useful resources:

|Name|Description|
|----------|----------|
| Additional learnR tutorials (available on SciServer and GitHub, along with the miniCURE materials)|Variety of topics, including basics of vectors, dataframes, and functions as well as introducing R Notebooks.|
|[Introduction to data analysis with R and Bioconductor](https://carpentries-incubator.github.io/bioc-intro)|Two day hands-on workshop|
|[swirl](https://swirlstats.com)|Interactive tutorials for use in any R Console covering base R|
|[R for Data Science](https://r4ds.hadley.nz)|Foundational book covering tidyverse|

### Additional Resources{-}

|Name|Description|
|----------|----------|
|[Understanding Science 101](https://undsci.berkeley.edu/understanding-science-101/)|Website explaining “how science works”|
|[Next Generation Sequencing Quality Analysis with Emoji](https://doi.org/10.24918/cs.2021.17)|CourseSource lesson|
|[RNA-seq Data Analysis Tutorial Using Galaxy](https://doi.org/10.24918/cs.2019.13)|CourseSource lesson|
|[Analyzing RNA-seq data with DESeq2](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html)|DESeq2 vignette|
|[Biomedical Knowledge Mining using GOSemSim and clusterProfiler](https://yulab-smu.top/biomedical-knowledge-mining-book)|clusterProfiler book|
|[RNA-seq analysis with Bioconductor](https://carpentries-incubator.github.io/bioc-rnaseq)|Two day hands-on workshop|
|[R for Data Science](https://r4ds.hadley.nz/)|Foundational book covering tidyverse|

