# Biological Databases

## Purpose 

In this activity, students  will learn to search the same online databases used by scientists to collect information about a set of genes and present them to your group. This will give you an opportunity to engage in inquiry-based learning and apply the concepts in molecular biology and genetics from this course.

## Learning Objectives 

1. Use online databases to look up information about a gene.

## Activity 1 - Databases

Estimated time: 15 min

1. Follow [these directions](https://docs.google.com/document/d/1nQ-wd4hX0Xtd4mfloXcpbbtK_CqDzY874oqmBYql1M8){target="_blank"} to launch your first LearnR tutorial: Biological Databases Tutorial.
1. To move through the activities click "Continue" at the bottom of the screen. When you are done with a topic, click "Next Topic" to move on.
1. As you complete the tutorial, fill in the table below. This will help you know which database to go back to later on.

Table 1. Databases 

| Database            | Description |
| --------------------|-------------|
| GenBank             |             |
| OMIM                |             |
| Human Protein Atlas |             |
| PDB                 |             |

## Activity 2 - FlyBase

Estimated time: 15 min

1. Work through the FlyBase Tutorial in SciServer.
1. To move through the activities click "Continue" at the bottom of the screen. When you are done with a topic, click "Next Topic" to move on.

::: {.reflection}
Observations

1. What is one question you have about using FlyBase?
1. What is something that surprised you or that you found interesting about using FlyBase?
:::

## Activity 3 - Human Protein Atlas

Estimated time: 15 min

1. Work through the Human Protein Atlas in SciServer.
1. To move through the activities click "Continue" at the bottom of the screen. When you are done with a topic, click "Next Topic" to move on.

::: {.reflection}
Observations

1. What is one question you have about using HPA?
1. What is something that surprised you or that you found interesting about using HPA?
:::

## Activity 4 - Research a Gene!

Estimated time: 45  min

1. Before getting started on this activity, your instructor will assign your group a letter that corresponds to a group of  4 genes.

::: {.notice}
Group Assigned Letter
:::

2. [Look up your letter here](#table-of-genes-for-activity-4) and write the names of the four genes your group is assigned at the top of each column in the table below.
3. In your group, assign each student one of the four genes to research.

::: {.notice}
Individual Assigned Gene
:::

4. Use FlyBase to look up the information in Table 3 below.
5. Use HPA to look up the information in Table 4 below.

Table 2. FlyBase Information

| Category | Information |
|----------|-------------|
| **General Information** | |
| Full Gene Name | |
| FlyBase ID | |
| Sequence Location | |
| **Function** | |
| Biological Process | |
| Cellular Component | |
| **Expression Data** | |
| Anatomical Expression | |
| Developmental Stage | |
| **Orthologs** | |
| Orthologs in other species | |
| Human Orthologs | |

Table 3. Human Protein Atlas

| Category | Information |
|----------|-------------|
| Function | |
| Is the gene tissue specific? Which tissue? | |
| Where is it localized in cells? | |

## Activity 5 - Present to your Group

Estimated time: 15 min

1. Present your gene to your group.
1. Take turns presenting your genes amongst your group and decide on one gene that you think is the most interesting.

## Activity 6 - Class Presentation

Estimated time:30 mins

1. With your group, create a short presentation to present your chosen gene to the class. 
1. Your presentation should have about four slides and be thorough:
    1. Slide 1: The GENE you picked to share with your group, your name and date
    1. Slide 2 - 4: Present the information you collected about the gene.  For full credit, include relevant images/ diagrams on your slides. 
1. One student in the group should post  your slides on Canvas to the discussion board. Make sure you mention everyone in your group by name so they also get credit for the presentation.

## Table of Genes for Activity 4

| Group | Pathway | Gene -if there is "()" use the name in "()" to search |
|--|--|--|
| A | Insulin signaling | DILP2 (search for ILP2) |
| A | Insulin signaling | DILP3 (search for ILP3) |
| A | glycolysis | hexokinase C |
| A | glycolysis | hexokinase A |
| B | glycolysis | GAPDH (CG9042) |
| B | FOXO targets | hydroxyphenylpyruvate dehydrogenase |
| B | FOXO targets | carnitine palmitoyl transferase (CG12428) |
| B | FOXO targets | pantothenate kinase acyl coA dehydrogenase (CG9547) |
| C | FOXO targets | TAG lipase 4 |
| C | FOXO targets | 4EBP |
| C | fat synthesis | fatty acid synthases |
| C | fat synthesis | acetyl coA carboxylase |
| D | fat synthesis | ChREBP |
| D | fat synthesis | stearoyl coA desaturases (CG5887) |
| D | fat synthesis | stearoyl coA desaturases (CG9743) |
| D | fat storage | TAG lipases (CG8093) |
| E | fat storage | TAG lipases (CG6277) |
| E | fat storage | perilipin Lsd-1 |
| E | lipid mobilization | AKHR |
| E | lipid mobilization | carnitine palmitoyl transferase (CG 12891) |
| F | lipid mobilization | carnitine palmitoyl transferase (CG12428) |
| F | lipid mobilization | acyl coA dehydrogenases (CG7461) |
| F | lipid mobilization | acyl coA dehydrogenases (CG12262) |
| F | lipid mobilization | y-butyrobetaine dioxygenases (CG5321) |
| G | lipid mobilization | y-butyrobetaine dioxygenases (CG14630 |
| G | glycogenolysis | amyloglucosidase |
| G | glycogenolysis | glycogen phosphorylase |
| G | gluconeogenesis | PEPCK |
| H | gluconeogenesis | fructose-1,6-bisphosphatase |
| H | trehalose synthesis | trehalose-6-phosphate synthase |
| H | trehalose synthesis | trehalose transporter 1 |
| H | trehalose synthesis | trehalase |

## Contributions and Affiliations

- Rosa Alcazar, Ph.D., Clovis Community College
- Katherine Cox, Ph.D., John Hopkins
- Stephanie R. Coffman, Ph.D., Clovis Community College

Last Revised: September 2021
