# Instructor Guide {-}

C-MOOR miniCURE content overview.

### Content overview {-}

| **Name** | **Length** | **Notes** |
| :--- | :---: | :---: |
| [Overview / Scientific Process](https://science.c-moor.org/miniCURE-RNA-seq/introduction.html) | 1 hr | |
| [#1: Scientific Literature](https://science.c-moor.org/miniCURE-RNA-seq/scientific-literature.html) | Full lab | Pre-lab: Scientific Literature |
| [#2: Model Organisms and Databases](https://science.c-moor.org/miniCURE-RNA-seq/model-organisms-and-databases.html) | Full lab | Pre-lab: Model Organisms |
| [#3: RNA-seq Analysis](https://science.c-moor.org/miniCURE-RNA-seq/rna-seq-analysis.html) | Full lab | Pre-lab: Intro to RNA-seq |
| [#4: Differential Gene Expression](https://science.c-moor.org/miniCURE-RNA-seq/differential-gene-expression.html) | Full lab | |
| [#5: Kickstart Project Work](https://science.c-moor.org/miniCURE-RNA-seq/kickstart-project-work.html) | Flexible | |
| [Tutorial Center](https://science.c-moor.org/miniCURE-RNA-seq/tutorial-center.html) | Flexible | Optional |
| [Poster presentation](https://www.cloviscollege.edu/landing/stem-research-symposium-2023.html) | Flexible | Optional |

Some examples of how we have incorporated the labs into a course can be seen in [Sample schedules](#sample-schedules)

### Sample schedules {#onboard -}

Here is an example of how this RNA-seq miniCURE was incorporated into the BIOL11A "Biology for Science Majors" lab at Clovis Community College and into the BIO239 "Genetics" lab at Notre Dame of Maryland University.

"Optional" refers to activities related to the mini-CURE that are not part of the core curriculum (a pre- and post- test surveying student experiences, a visit to the on-campus "tutorial center" where students can receive help and advice, and the printing and presenting of posters).

#### Clovis Community College example {-}

| **Spring 2023** | **Lab #** | **Lab Topic** | **miniCURE** | **Optional** |
| :---: | :---: | :---: | :---: | :---: |
| Jan 11 | 1 | Micropipetting           | [Overview / Scientific Process](https://science.c-moor.org/miniCURE-RNA-seq/introduction.html) |          |
| Jan 18 | 2 | Quantitative Data Analysis | | |
| Jan 25 | 3 | Microscopes and Cells | | |
| Feb 1 | 4 | Diffusion and Osmosis | | |
| Feb 8 | 5 | Enzymes | | |
| Feb 15 | 6 | Cellular Response and Photosynthesis | Assign Onboarding | Pre-test |
| Feb 22 | 7 | | [#1: Scientific Literature](https://science.c-moor.org/miniCURE-RNA-seq/scientific-literature.html) | |
| Mar 1 | 8 | Bacterial Transformation and Exam 1 | | |
| Mar 8 | 9 | | [#2: Model Organisms and Databases](https://science.c-moor.org/miniCURE-RNA-seq/model-organisms-and-databases.html) | |
| Mar 15 | 10 | | [#3: RNA-seq Analysis](https://science.c-moor.org/miniCURE-RNA-seq/rna-seq-analysis.html) | |
| Mar 22 | 11 | | [#4: Differential Gene Expression](https://science.c-moor.org/miniCURE-RNA-seq/differential-gene-expression.html) | |
| Mar 29 | 12 | DNA Extractions and PCR | [#5: Kickstart Project Work](https://science.c-moor.org/miniCURE-RNA-seq/kickstart-project-work.html) | |
| Apr 12 | 13 | Mendelian Genetics | | [Tutorial Center](https://science.c-moor.org/miniCURE-RNA-seq/tutorial-center.html) |
| Apr 19 | | | Project Check-in | |
| Apr 26 | 14 | Mitosis and Meiosis | Project Due | |
| May 3 | 15 | Population Genetics | | Submit for Printing |
| May 10 | | Exam 2 | | |
| May 12 | | | | [Poster Presentation](https://www.cloviscollege.edu/landing/stem-research-symposium-2023.html), Post-test |

#### Notre Dame of Maryland University example {-}

| **Week** | **Date** | **Lab Subject** | **miniCURE** | **Reading** | **Due** |
| :---: | :---: | :---: |  :---: | :---: | :---: |
| 1 | Jan 26 | Tools of Molecular Biology I, II | | Syllabus | |
| 2 | Feb 2 | Tools of Molecular Biology III |  | Handout | |
| 3| Feb 9 | Intro: Plasmids, Cloning, Transformation - Gel Electrophoresis; PCR | [Overview / Scientific Process](https://science.c-moor.org/miniCURE-RNA-seq/introduction.html) | Handout | Tools I: Sign up for SciServer  |
| 4 | Feb 16 | Tools of Molecular Biology III Bioinformatics: Literature | [#1: Scientific Literature](https://science.c-moor.org/miniCURE-RNA-seq/scientific-literature.html)  | | [Pre-lab Module](https://science.c-moor.org/miniCURE-RNA-seq/pre-lab-scientific-literature.html) |
| 5 | Feb 23 | Bioinformatics: Model Organisms and Databases | [#2: Model Organisms and Databases](https://science.c-moor.org/miniCURE-RNA-seq/model-organisms-and-databases.html)  | [Pre-lab Module](https://science.c-moor.org/miniCURE-RNA-seq/pre-lab-model-organisms.html)  | Tools II, III |
| 6 | Mar 2 | Bioinformatics: RNA-seq | [#3: RNA-seq Analysis](https://science.c-moor.org/miniCURE-RNA-seq/rna-seq-analysis.html) | [Pre-lab Module](https://science.c-moor.org/miniCURE-RNA-seq/pre-lab-intro-to-rna-seq.html) | | 
| 7 | Mar 9 | Bioinformatics: Differential expression | [#4: Differential Gene Expression](https://science.c-moor.org/miniCURE-RNA-seq/differential-gene-expression.html)  | Lab Modules  | Bioinformatics: abstract draft | 
| 8 | Mar 16 | Bioinformatics: Project development, and pour gels | [#5: Kickstart Project Work](https://science.c-moor.org/miniCURE-RNA-seq/kickstart-project-work.html)  |  Pre-lab Module; Handout | |
| 9 | Mar 23 | Restriction digest, run gels | | Handout | Practical |
| 10 | Mar 30 | Band Isolation and ligation | | Handout | Poster Draft |
| 11 | Apr 6 | Spring Break | | | |
| 12 | Apr 13 | Transformation |  | Handout | |
| 13 | Apr 20 | Mini-preps, sequencing, DNA Quantification |  | Handout | |
| 14 | Apr 27 | Restriction digest, sequencing prep/analysis; Presentations |  | Handout | [Poster Presentations](https://www.cloviscollege.edu/landing/stem-research-symposium-2023.html) |
| 15 | May 4 | Practical | | | |
